/**
 * The GhostGet launch social kit, cut straight from the beats: X, Bluesky,
 * and Threads threads, one LinkedIn post, the Product Hunt fields, and a
 * fact sheet for a person writing Show HN or a first comment.
 *
 * `bun run launch:kit` writes it to kb/launch/social-kit.md.
 */
import { assertLaunchKit, buildSocialKit, type LaunchMessaging } from "@hraness/design-kit/launch";
import { resolvedLaunchBeats } from "./beats.ts";
import { LAUNCH_CANONICAL_URL, LAUNCH_RELEASE, launchFacts } from "./facts.ts";
import { marketing } from "../portfolio-copy";

/** Keep the dated launch brief's tagline; current identity and meta come from the portfolio. */
export const launchMessaging = Object.freeze({
  names: Object.freeze({ name: marketing.names.name }),
  tagline: "wget for the ghost in the machine",
  meta: marketing.meta,
}) satisfies LaunchMessaging;

export const socialKit = buildSocialKit(resolvedLaunchBeats, launchMessaging, LAUNCH_RELEASE, LAUNCH_CANONICAL_URL);

assertLaunchKit(resolvedLaunchBeats, socialKit, {
  status: LAUNCH_RELEASE.status,
  publicInstall: LAUNCH_RELEASE.publicInstall,
  tagline: launchMessaging.tagline,
  canonicalUrl: LAUNCH_CANONICAL_URL,
});

const block = (text: string): string => ["```text", text, "```"].join("\n");
const thread = (name: string, posts: readonly string[]): string[] => [
  `## ${name}`,
  "",
  ...posts.flatMap((post, index) => [`Post ${index + 1} of ${posts.length}, ${[...post].length} characters`, "", block(post), ""]),
];

/** The kit as Markdown for kb/launch/social-kit.md. Every line comes from the beats and facts. */
export function renderSocialKitMarkdown(): string {
  return [
    "# GhostGet launch social kit",
    "",
    "Generated by `bun run launch:kit` from `website/launch/beats.ts` and `website/launch/facts.ts`. Do not edit by hand; change the beats or facts and run it again.",
    "",
    "Posts go out from the @hraness account. Each post matches one section of https://ghostget.com/blog/introducing-ghostget/ and can deep-link to it with `#beat-<id>`. Show HN and the Product Hunt first comment are written by a person from the fact sheet below.",
    "",
    ...thread("X thread", socialKit.x),
    ...thread("Bluesky thread", socialKit.bluesky),
    ...thread("Threads thread", socialKit.threads),
    "## LinkedIn post",
    "",
    block(socialKit.linkedin),
    "",
    "## Product Hunt",
    "",
    `Tagline: ${socialKit.productHunt.tagline}`,
    "",
    "Description:",
    "",
    block(socialKit.productHunt.description),
    "",
    `Topics: ${socialKit.productHunt.tags.join(", ")}`,
    "",
    "## Show HN and first comment fact sheet",
    "",
    ...socialKit.showHnFacts.map((fact) => `- ${fact}`),
    "",
    "## Beats",
    "",
    ...resolvedLaunchBeats.map((beat, index) => `${index + 1}. ${beat.headline} (#beat-${beat.id})`),
    "",
    "## Facts and their records",
    "",
    ...Object.entries(launchFacts).map(([name, fact]) => `- ${name}: ${fact.value}. ${fact.source}`),
    "",
  ].join("\n");
}

if (import.meta.main) {
  const { mkdir, writeFile } = await import("node:fs/promises");
  const { dirname, join } = await import("node:path");
  const target = join(import.meta.dir, "../../kb/launch/social-kit.md");
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, renderSocialKitMarkdown());
  console.log(`Wrote ${target}`);
}
